-- SA Public Portfolio / Supabase schema
-- Run this in Supabase SQL Editor.
-- IMPORTANT: Enable Anonymous Sign-ins in Authentication > Providers > Anonymous.

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  wallet_address text unique not null,
  nickname text not null default 'Citizen',
  created_at timestamptz not null default now()
);

create table if not exists public.wall_posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  wallet_address text not null,
  type text not null default 'message' check (type = 'message'),
  content text not null check (char_length(content) between 1 and 500),
  created_at timestamptz not null default now()
);

create table if not exists public.donations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  wallet_address text not null,
  amount_ton numeric(30,9) not null check (amount_ton > 0),
  tx_boc text,
  created_at timestamptz not null default now()
);

create index if not exists wall_posts_created_idx on public.wall_posts(created_at desc);
create index if not exists donations_created_idx on public.donations(created_at desc);

alter table public.profiles enable row level security;
alter table public.wall_posts enable row level security;
alter table public.donations enable row level security;

-- Public can read the wall/profile data.
create policy "public read profiles" on public.profiles
for select using (true);

create policy "public read wall posts" on public.wall_posts
for select using (true);

create policy "public read donations" on public.donations
for select using (true);

-- A signed-in anonymous browser session can only write its own rows.
create policy "own profile insert" on public.profiles
for insert to authenticated
with check (auth.uid() = user_id);

create policy "own profile update" on public.profiles
for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "own post insert" on public.wall_posts
for insert to authenticated
with check (auth.uid() = user_id);

create policy "own donation insert" on public.donations
for insert to authenticated
with check (auth.uid() = user_id);

-- Optional: tighten profile wallet spoofing later with TON Proof.
-- The current MVP uses the connected TON address as the displayed identity.
